packages:
  - packages/*

ignoredBuiltDependencies:
  - esbuild
onlyBuiltDependencies:
  - es5-ext
  - msw
  - puppeteer
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
