/**
 * Post-processes orval's generated model directory, merging all individual
 * schema files into a single model/index.ts. This avoids 900+ files while
 * preserving every exported type.
 *
 * Why: orval (tags-split mode) creates one file per OpenAPI schema object.
 * Rust/utoipa backends produce many nullable-field helper types which bloat
 * the directory. Merging into one file keeps the import path unchanged:
 *   import type { Foo } from '~/shared/api/generated/model'
 */

import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const modelDir = new URL(
  '../src/shared/api/generated/model',
  import.meta.url,
).pathname.replace(/^\/([A-Z]:)/, '$1') // fix Windows /C:/... path

const files = readdirSync(modelDir)
  .filter(f => f.endsWith('.ts') && f !== 'index.ts')
  .sort()

if (files.length === 0) {
  console.log('No schema files found to consolidate.')
  process.exit(0)
}

const HEADER_RE = /^\/\*\*[\s\S]*?\*\/\n*/
const INTRA_IMPORT_RE = /^import type \{[^}]+\} from '\.\/[^']+';?\n?/gm

const blocks = []

for (const file of files) {
  const content = readFileSync(join(modelDir, file), 'utf8')
  const stripped = content
    .replace(HEADER_RE, '')
    .replace(INTRA_IMPORT_RE, '')
    .trim()

  if (stripped)
    blocks.push(stripped)
}

const header = `/**
 * Generated by orval v7.x 🍺 — consolidated by consolidate-model.mjs
 * Do not edit manually. Run \`pnpm api:generate\` to regenerate.
 */\n\n`

writeFileSync(join(modelDir, 'index.ts'), header + blocks.join('\n\n') + '\n')

for (const file of files) {
  rmSync(join(modelDir, file))
}

console.log(
  `✅ Consolidated ${files.length} schema files into model/index.ts`,
)
