use sea_orm::{
  ActiveModelTrait, ActiveValue::Set, ColumnTrait, ConnectionTrait, EntityName, ModelTrait,
  QueryFilter,
};
use serde::Serialize;
use serde_json::Value;
use uuid::Uuid;

use super::AuditService;
use crate::{
  api::ApiError,
  context::audit::{current_actor_id, current_origin_db_id},
  entities::audit_log,
  enums::AuditAction,
};

fn model_table_name<M: ModelTrait>() -> String {
  <<M as ModelTrait>::Entity as EntityName>::table_name(&Default::default()).to_string()
}

/// Entity-level INSERT audit hook — called from `after_save` generated by `#[handle_service_fields]`.
///
/// Only creates an audit log when an audit context exists (actor_id + origin_db_id are set).
/// Returns Ok(()) silently when no context (e.g., during sync restore) or on any error
/// (best-effort at entity level; service layer provides mandatory audit for updates/deletes).
pub async fn entity_after_insert_hook<C: ConnectionTrait, M: ModelTrait + Serialize>(
  conn: &C,
  record_id: Uuid,
  model: &M,
) -> Result<(), sea_orm::DbErr> {
  let Some(actor_id) = current_actor_id() else {
    return Ok(());
  };
  let Some(origin_db_id) = current_origin_db_id() else {
    return Ok(());
  };

  let table_name = model_table_name::<M>();

  let new_val = match serde_json::to_value(model) {
    Ok(v) => v,
    Err(_) => return Ok(()),
  };

  let base_ids =
    super::routing::resolve_target_base_ids(conn, &table_name, record_id, Some(&new_val))
      .await
      .unwrap_or_default();
  let target_base_ids = normalize_target_base_ids(&base_ids);

  let role_weight = super::routing::resolve_role_weight(conn, actor_id)
    .await
    .unwrap_or(0);

  audit_log::ActiveModel {
    table_name: Set(table_name),
    record_id: Set(record_id),
    action: Set(AuditAction::Insert),
    old_values: Set(None),
    new_values: Set(Some(new_val)),
    target_base_ids: Set(target_base_ids),
    user_role_weight: Set(role_weight),
    user_id: Set(actor_id),
    origin_db_id: Set(origin_db_id),
    ..Default::default()
  }
  .insert(conn)
  .await?;

  Ok(())
}

fn serialize_snapshot<M: Serialize>(model: &M) -> Result<Value, ApiError> {
  serde_json::to_value(model)
    .map_err(|error| ApiError::BadRequest(format!("Failed to serialize audit snapshot: {error}")))
}

fn normalize_target_base_ids(base_ids: &[Uuid]) -> String {
  crate::services::sync::helpers::normalize_target_base_ids(
    &base_ids
      .iter()
      .map(|id| id.to_string())
      .collect::<Vec<_>>()
      .join(","),
  )
}

impl AuditService {
  // INSERT audit logs are created automatically by the entity's after_save hook
  // (generated by #[handle_service_fields] macro). No manual registration needed.

  pub async fn register_update<C: ConnectionTrait, M: ModelTrait + serde::Serialize>(
    &self,
    conn: &C,
    record_id: Uuid,
    old_model: &M,
    new_model: &M,
  ) -> Result<(), ApiError> {
    let table_name = model_table_name::<M>();

    let old_val = serialize_snapshot(old_model)?;
    let new_val = serialize_snapshot(new_model)?;

    if old_val == new_val {
      return Ok(());
    }

    self
      .register_action(
        conn,
        &table_name,
        record_id,
        AuditAction::Update,
        Some(old_val),
        Some(new_val),
      )
      .await
  }

  pub async fn register_delete<C: ConnectionTrait, M: ModelTrait + serde::Serialize>(
    &self,
    conn: &C,
    record_id: Uuid,
    old_model: &M,
  ) -> Result<(), ApiError> {
    let table_name = model_table_name::<M>();

    let old_val = serialize_snapshot(old_model)?;

    self
      .register_action(
        conn,
        &table_name,
        record_id,
        AuditAction::HardDelete,
        Some(old_val),
        None,
      )
      .await
  }

  async fn register_action<C: ConnectionTrait>(
    &self,
    conn: &C,
    table_name: &str,
    record_id: Uuid,
    action: AuditAction,
    old_values: Option<Value>,
    new_values: Option<Value>,
  ) -> Result<(), ApiError> {
    let actor_id = current_actor_id()
      .ok_or_else(|| ApiError::Unauthorized("Missing authenticated actor context".to_string()))?;
    let origin_db_id = current_origin_db_id().unwrap_or(self.cfg.node.db_id);

    // Resolve routing envelope: which bases are affected by this change?
    let base_ids =
      super::routing::resolve_target_base_ids(conn, table_name, record_id, new_values.as_ref())
        .await
        .unwrap_or_default();
    let target_base_ids = normalize_target_base_ids(&base_ids);

    // Resolve role weight for conflict resolution
    let role_weight = super::routing::resolve_role_weight(conn, actor_id)
      .await
      .unwrap_or(0);

    audit_log::ActiveModel {
      table_name: Set(table_name.to_string()),
      record_id: Set(record_id),
      action: Set(action),
      old_values: Set(old_values),
      new_values: Set(new_values),
      target_base_ids: Set(target_base_ids),
      user_role_weight: Set(role_weight),
      user_id: Set(actor_id),
      origin_db_id: Set(origin_db_id),
      ..Default::default()
    }
    .insert(conn)
    .await?;

    Ok(())
  }

  /// Re-resolve and update routing envelopes for a document header's audit logs.
  ///
  /// In composite creates, the document header is audited before child items exist,
  /// so its routing envelope is initially empty. Call this after all items are created
  /// to backfill the correct routing based on the now-existing items.
  pub async fn backfill_document_routing<C: ConnectionTrait>(
    &self,
    conn: &C,
    table_name: &str,
    document_id: Uuid,
  ) -> Result<(), ApiError> {
    let base_ids =
      super::routing::resolve_target_base_ids(conn, table_name, document_id, None).await?;
    if base_ids.is_empty() {
      return Ok(());
    }
    let target = normalize_target_base_ids(&base_ids);

    let logs: Vec<audit_log::ModelEx> = audit_log::Entity::load()
      .filter(audit_log::Column::TableName.eq(table_name))
      .filter(audit_log::Column::RecordId.eq(document_id))
      .filter(audit_log::Column::Action.eq(AuditAction::Insert))
      .all(conn)
      .await?;

    for log in logs {
      if log.target_base_ids != target {
        let mut am = audit_log::ActiveModel {
          id: Set(log.id),
          ..Default::default()
        };
        am.target_base_ids = Set(target.clone());
        am.update(conn).await?;
      }
    }

    Ok(())
  }
}
