/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSetupRouteImport } from './routes/(auth)/setup'
import { Route as authInitRouteImport } from './routes/(auth)/init'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedLedgerIndexRouteImport } from './routes/_authenticated/ledger/index'
import { Route as AuthenticatedTransportTruckWaybillsIndexRouteImport } from './routes/_authenticated/transport/truck-waybills/index'
import { Route as AuthenticatedTransportRailWaybillsIndexRouteImport } from './routes/_authenticated/transport/rail-waybills/index'
import { Route as AuthenticatedSystemUsersIndexRouteImport } from './routes/_authenticated/system/users/index'
import { Route as AuthenticatedSystemSyncIndexRouteImport } from './routes/_authenticated/system/sync/index'
import { Route as AuthenticatedDocumentsPhysicalTransferIndexRouteImport } from './routes/_authenticated/documents/physical-transfer/index'
import { Route as AuthenticatedDocumentsOwnershipTransferIndexRouteImport } from './routes/_authenticated/documents/ownership-transfer/index'
import { Route as AuthenticatedDocumentsInventoryReconciliationIndexRouteImport } from './routes/_authenticated/documents/inventory-reconciliation/index'
import { Route as AuthenticatedDocumentsDispatchIndexRouteImport } from './routes/_authenticated/documents/dispatch/index'
import { Route as AuthenticatedDocumentsBlendingIndexRouteImport } from './routes/_authenticated/documents/blending/index'
import { Route as AuthenticatedDocumentsAcceptanceIndexRouteImport } from './routes/_authenticated/documents/acceptance/index'
import { Route as AuthenticatedCatalogWarehousesIndexRouteImport } from './routes/_authenticated/catalog/warehouses/index'
import { Route as AuthenticatedCatalogStoragesIndexRouteImport } from './routes/_authenticated/catalog/storages/index'
import { Route as AuthenticatedCatalogProductsIndexRouteImport } from './routes/_authenticated/catalog/products/index'
import { Route as AuthenticatedCatalogProductTypesIndexRouteImport } from './routes/_authenticated/catalog/product-types/index'
import { Route as AuthenticatedCatalogProductGroupsIndexRouteImport } from './routes/_authenticated/catalog/product-groups/index'
import { Route as AuthenticatedCatalogPortsIndexRouteImport } from './routes/_authenticated/catalog/ports/index'
import { Route as AuthenticatedCatalogCompaniesIndexRouteImport } from './routes/_authenticated/catalog/companies/index'
import { Route as AuthenticatedCatalogBasesIndexRouteImport } from './routes/_authenticated/catalog/bases/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSetupRoute = authSetupRouteImport.update({
  id: '/(auth)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const authInitRoute = authInitRouteImport.update({
  id: '/(auth)/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLedgerIndexRoute =
  AuthenticatedLedgerIndexRouteImport.update({
    id: '/ledger/',
    path: '/ledger/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportTruckWaybillsIndexRoute =
  AuthenticatedTransportTruckWaybillsIndexRouteImport.update({
    id: '/transport/truck-waybills/',
    path: '/transport/truck-waybills/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportRailWaybillsIndexRoute =
  AuthenticatedTransportRailWaybillsIndexRouteImport.update({
    id: '/transport/rail-waybills/',
    path: '/transport/rail-waybills/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersIndexRoute =
  AuthenticatedSystemUsersIndexRouteImport.update({
    id: '/system/users/',
    path: '/system/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemSyncIndexRoute =
  AuthenticatedSystemSyncIndexRouteImport.update({
    id: '/system/sync/',
    path: '/system/sync/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsPhysicalTransferIndexRoute =
  AuthenticatedDocumentsPhysicalTransferIndexRouteImport.update({
    id: '/documents/physical-transfer/',
    path: '/documents/physical-transfer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsOwnershipTransferIndexRoute =
  AuthenticatedDocumentsOwnershipTransferIndexRouteImport.update({
    id: '/documents/ownership-transfer/',
    path: '/documents/ownership-transfer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsInventoryReconciliationIndexRoute =
  AuthenticatedDocumentsInventoryReconciliationIndexRouteImport.update({
    id: '/documents/inventory-reconciliation/',
    path: '/documents/inventory-reconciliation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDispatchIndexRoute =
  AuthenticatedDocumentsDispatchIndexRouteImport.update({
    id: '/documents/dispatch/',
    path: '/documents/dispatch/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsBlendingIndexRoute =
  AuthenticatedDocumentsBlendingIndexRouteImport.update({
    id: '/documents/blending/',
    path: '/documents/blending/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsAcceptanceIndexRoute =
  AuthenticatedDocumentsAcceptanceIndexRouteImport.update({
    id: '/documents/acceptance/',
    path: '/documents/acceptance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogWarehousesIndexRoute =
  AuthenticatedCatalogWarehousesIndexRouteImport.update({
    id: '/catalog/warehouses/',
    path: '/catalog/warehouses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogStoragesIndexRoute =
  AuthenticatedCatalogStoragesIndexRouteImport.update({
    id: '/catalog/storages/',
    path: '/catalog/storages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductsIndexRoute =
  AuthenticatedCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductTypesIndexRoute =
  AuthenticatedCatalogProductTypesIndexRouteImport.update({
    id: '/catalog/product-types/',
    path: '/catalog/product-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductGroupsIndexRoute =
  AuthenticatedCatalogProductGroupsIndexRouteImport.update({
    id: '/catalog/product-groups/',
    path: '/catalog/product-groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogPortsIndexRoute =
  AuthenticatedCatalogPortsIndexRouteImport.update({
    id: '/catalog/ports/',
    path: '/catalog/ports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogCompaniesIndexRoute =
  AuthenticatedCatalogCompaniesIndexRouteImport.update({
    id: '/catalog/companies/',
    path: '/catalog/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogBasesIndexRoute =
  AuthenticatedCatalogBasesIndexRouteImport.update({
    id: '/catalog/bases/',
    path: '/catalog/bases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/init': typeof authInitRoute
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/ledger/': typeof AuthenticatedLedgerIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/catalog/bases/': typeof AuthenticatedCatalogBasesIndexRoute
  '/catalog/companies/': typeof AuthenticatedCatalogCompaniesIndexRoute
  '/catalog/ports/': typeof AuthenticatedCatalogPortsIndexRoute
  '/catalog/product-groups/': typeof AuthenticatedCatalogProductGroupsIndexRoute
  '/catalog/product-types/': typeof AuthenticatedCatalogProductTypesIndexRoute
  '/catalog/products/': typeof AuthenticatedCatalogProductsIndexRoute
  '/catalog/storages/': typeof AuthenticatedCatalogStoragesIndexRoute
  '/catalog/warehouses/': typeof AuthenticatedCatalogWarehousesIndexRoute
  '/documents/acceptance/': typeof AuthenticatedDocumentsAcceptanceIndexRoute
  '/documents/blending/': typeof AuthenticatedDocumentsBlendingIndexRoute
  '/documents/dispatch/': typeof AuthenticatedDocumentsDispatchIndexRoute
  '/documents/inventory-reconciliation/': typeof AuthenticatedDocumentsInventoryReconciliationIndexRoute
  '/documents/ownership-transfer/': typeof AuthenticatedDocumentsOwnershipTransferIndexRoute
  '/documents/physical-transfer/': typeof AuthenticatedDocumentsPhysicalTransferIndexRoute
  '/system/sync/': typeof AuthenticatedSystemSyncIndexRoute
  '/system/users/': typeof AuthenticatedSystemUsersIndexRoute
  '/transport/rail-waybills/': typeof AuthenticatedTransportRailWaybillsIndexRoute
  '/transport/truck-waybills/': typeof AuthenticatedTransportTruckWaybillsIndexRoute
}
export interface FileRoutesByTo {
  '/init': typeof authInitRoute
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/ledger': typeof AuthenticatedLedgerIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/catalog/bases': typeof AuthenticatedCatalogBasesIndexRoute
  '/catalog/companies': typeof AuthenticatedCatalogCompaniesIndexRoute
  '/catalog/ports': typeof AuthenticatedCatalogPortsIndexRoute
  '/catalog/product-groups': typeof AuthenticatedCatalogProductGroupsIndexRoute
  '/catalog/product-types': typeof AuthenticatedCatalogProductTypesIndexRoute
  '/catalog/products': typeof AuthenticatedCatalogProductsIndexRoute
  '/catalog/storages': typeof AuthenticatedCatalogStoragesIndexRoute
  '/catalog/warehouses': typeof AuthenticatedCatalogWarehousesIndexRoute
  '/documents/acceptance': typeof AuthenticatedDocumentsAcceptanceIndexRoute
  '/documents/blending': typeof AuthenticatedDocumentsBlendingIndexRoute
  '/documents/dispatch': typeof AuthenticatedDocumentsDispatchIndexRoute
  '/documents/inventory-reconciliation': typeof AuthenticatedDocumentsInventoryReconciliationIndexRoute
  '/documents/ownership-transfer': typeof AuthenticatedDocumentsOwnershipTransferIndexRoute
  '/documents/physical-transfer': typeof AuthenticatedDocumentsPhysicalTransferIndexRoute
  '/system/sync': typeof AuthenticatedSystemSyncIndexRoute
  '/system/users': typeof AuthenticatedSystemUsersIndexRoute
  '/transport/rail-waybills': typeof AuthenticatedTransportRailWaybillsIndexRoute
  '/transport/truck-waybills': typeof AuthenticatedTransportTruckWaybillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/init': typeof authInitRoute
  '/(auth)/setup': typeof authSetupRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ledger/': typeof AuthenticatedLedgerIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/catalog/bases/': typeof AuthenticatedCatalogBasesIndexRoute
  '/_authenticated/catalog/companies/': typeof AuthenticatedCatalogCompaniesIndexRoute
  '/_authenticated/catalog/ports/': typeof AuthenticatedCatalogPortsIndexRoute
  '/_authenticated/catalog/product-groups/': typeof AuthenticatedCatalogProductGroupsIndexRoute
  '/_authenticated/catalog/product-types/': typeof AuthenticatedCatalogProductTypesIndexRoute
  '/_authenticated/catalog/products/': typeof AuthenticatedCatalogProductsIndexRoute
  '/_authenticated/catalog/storages/': typeof AuthenticatedCatalogStoragesIndexRoute
  '/_authenticated/catalog/warehouses/': typeof AuthenticatedCatalogWarehousesIndexRoute
  '/_authenticated/documents/acceptance/': typeof AuthenticatedDocumentsAcceptanceIndexRoute
  '/_authenticated/documents/blending/': typeof AuthenticatedDocumentsBlendingIndexRoute
  '/_authenticated/documents/dispatch/': typeof AuthenticatedDocumentsDispatchIndexRoute
  '/_authenticated/documents/inventory-reconciliation/': typeof AuthenticatedDocumentsInventoryReconciliationIndexRoute
  '/_authenticated/documents/ownership-transfer/': typeof AuthenticatedDocumentsOwnershipTransferIndexRoute
  '/_authenticated/documents/physical-transfer/': typeof AuthenticatedDocumentsPhysicalTransferIndexRoute
  '/_authenticated/system/sync/': typeof AuthenticatedSystemSyncIndexRoute
  '/_authenticated/system/users/': typeof AuthenticatedSystemUsersIndexRoute
  '/_authenticated/transport/rail-waybills/': typeof AuthenticatedTransportRailWaybillsIndexRoute
  '/_authenticated/transport/truck-waybills/': typeof AuthenticatedTransportTruckWaybillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/init'
    | '/setup'
    | '/sign-in'
    | '/ledger/'
    | '/settings/'
    | '/catalog/bases/'
    | '/catalog/companies/'
    | '/catalog/ports/'
    | '/catalog/product-groups/'
    | '/catalog/product-types/'
    | '/catalog/products/'
    | '/catalog/storages/'
    | '/catalog/warehouses/'
    | '/documents/acceptance/'
    | '/documents/blending/'
    | '/documents/dispatch/'
    | '/documents/inventory-reconciliation/'
    | '/documents/ownership-transfer/'
    | '/documents/physical-transfer/'
    | '/system/sync/'
    | '/system/users/'
    | '/transport/rail-waybills/'
    | '/transport/truck-waybills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/init'
    | '/setup'
    | '/sign-in'
    | '/'
    | '/ledger'
    | '/settings'
    | '/catalog/bases'
    | '/catalog/companies'
    | '/catalog/ports'
    | '/catalog/product-groups'
    | '/catalog/product-types'
    | '/catalog/products'
    | '/catalog/storages'
    | '/catalog/warehouses'
    | '/documents/acceptance'
    | '/documents/blending'
    | '/documents/dispatch'
    | '/documents/inventory-reconciliation'
    | '/documents/ownership-transfer'
    | '/documents/physical-transfer'
    | '/system/sync'
    | '/system/users'
    | '/transport/rail-waybills'
    | '/transport/truck-waybills'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/init'
    | '/(auth)/setup'
    | '/(auth)/sign-in'
    | '/_authenticated/'
    | '/_authenticated/ledger/'
    | '/_authenticated/settings/'
    | '/_authenticated/catalog/bases/'
    | '/_authenticated/catalog/companies/'
    | '/_authenticated/catalog/ports/'
    | '/_authenticated/catalog/product-groups/'
    | '/_authenticated/catalog/product-types/'
    | '/_authenticated/catalog/products/'
    | '/_authenticated/catalog/storages/'
    | '/_authenticated/catalog/warehouses/'
    | '/_authenticated/documents/acceptance/'
    | '/_authenticated/documents/blending/'
    | '/_authenticated/documents/dispatch/'
    | '/_authenticated/documents/inventory-reconciliation/'
    | '/_authenticated/documents/ownership-transfer/'
    | '/_authenticated/documents/physical-transfer/'
    | '/_authenticated/system/sync/'
    | '/_authenticated/system/users/'
    | '/_authenticated/transport/rail-waybills/'
    | '/_authenticated/transport/truck-waybills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authInitRoute: typeof authInitRoute
  authSetupRoute: typeof authSetupRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/setup': {
      id: '/(auth)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof authSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/init': {
      id: '/(auth)/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof authInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger/': {
      id: '/_authenticated/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof AuthenticatedLedgerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transport/truck-waybills/': {
      id: '/_authenticated/transport/truck-waybills/'
      path: '/transport/truck-waybills'
      fullPath: '/transport/truck-waybills/'
      preLoaderRoute: typeof AuthenticatedTransportTruckWaybillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transport/rail-waybills/': {
      id: '/_authenticated/transport/rail-waybills/'
      path: '/transport/rail-waybills'
      fullPath: '/transport/rail-waybills/'
      preLoaderRoute: typeof AuthenticatedTransportRailWaybillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users/': {
      id: '/_authenticated/system/users/'
      path: '/system/users'
      fullPath: '/system/users/'
      preLoaderRoute: typeof AuthenticatedSystemUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/sync/': {
      id: '/_authenticated/system/sync/'
      path: '/system/sync'
      fullPath: '/system/sync/'
      preLoaderRoute: typeof AuthenticatedSystemSyncIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/physical-transfer/': {
      id: '/_authenticated/documents/physical-transfer/'
      path: '/documents/physical-transfer'
      fullPath: '/documents/physical-transfer/'
      preLoaderRoute: typeof AuthenticatedDocumentsPhysicalTransferIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/ownership-transfer/': {
      id: '/_authenticated/documents/ownership-transfer/'
      path: '/documents/ownership-transfer'
      fullPath: '/documents/ownership-transfer/'
      preLoaderRoute: typeof AuthenticatedDocumentsOwnershipTransferIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/inventory-reconciliation/': {
      id: '/_authenticated/documents/inventory-reconciliation/'
      path: '/documents/inventory-reconciliation'
      fullPath: '/documents/inventory-reconciliation/'
      preLoaderRoute: typeof AuthenticatedDocumentsInventoryReconciliationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/dispatch/': {
      id: '/_authenticated/documents/dispatch/'
      path: '/documents/dispatch'
      fullPath: '/documents/dispatch/'
      preLoaderRoute: typeof AuthenticatedDocumentsDispatchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/blending/': {
      id: '/_authenticated/documents/blending/'
      path: '/documents/blending'
      fullPath: '/documents/blending/'
      preLoaderRoute: typeof AuthenticatedDocumentsBlendingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/acceptance/': {
      id: '/_authenticated/documents/acceptance/'
      path: '/documents/acceptance'
      fullPath: '/documents/acceptance/'
      preLoaderRoute: typeof AuthenticatedDocumentsAcceptanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/warehouses/': {
      id: '/_authenticated/catalog/warehouses/'
      path: '/catalog/warehouses'
      fullPath: '/catalog/warehouses/'
      preLoaderRoute: typeof AuthenticatedCatalogWarehousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/storages/': {
      id: '/_authenticated/catalog/storages/'
      path: '/catalog/storages'
      fullPath: '/catalog/storages/'
      preLoaderRoute: typeof AuthenticatedCatalogStoragesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/products/': {
      id: '/_authenticated/catalog/products/'
      path: '/catalog/products'
      fullPath: '/catalog/products/'
      preLoaderRoute: typeof AuthenticatedCatalogProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/product-types/': {
      id: '/_authenticated/catalog/product-types/'
      path: '/catalog/product-types'
      fullPath: '/catalog/product-types/'
      preLoaderRoute: typeof AuthenticatedCatalogProductTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/product-groups/': {
      id: '/_authenticated/catalog/product-groups/'
      path: '/catalog/product-groups'
      fullPath: '/catalog/product-groups/'
      preLoaderRoute: typeof AuthenticatedCatalogProductGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/ports/': {
      id: '/_authenticated/catalog/ports/'
      path: '/catalog/ports'
      fullPath: '/catalog/ports/'
      preLoaderRoute: typeof AuthenticatedCatalogPortsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/companies/': {
      id: '/_authenticated/catalog/companies/'
      path: '/catalog/companies'
      fullPath: '/catalog/companies/'
      preLoaderRoute: typeof AuthenticatedCatalogCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/bases/': {
      id: '/_authenticated/catalog/bases/'
      path: '/catalog/bases'
      fullPath: '/catalog/bases/'
      preLoaderRoute: typeof AuthenticatedCatalogBasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLedgerIndexRoute: typeof AuthenticatedLedgerIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedCatalogBasesIndexRoute: typeof AuthenticatedCatalogBasesIndexRoute
  AuthenticatedCatalogCompaniesIndexRoute: typeof AuthenticatedCatalogCompaniesIndexRoute
  AuthenticatedCatalogPortsIndexRoute: typeof AuthenticatedCatalogPortsIndexRoute
  AuthenticatedCatalogProductGroupsIndexRoute: typeof AuthenticatedCatalogProductGroupsIndexRoute
  AuthenticatedCatalogProductTypesIndexRoute: typeof AuthenticatedCatalogProductTypesIndexRoute
  AuthenticatedCatalogProductsIndexRoute: typeof AuthenticatedCatalogProductsIndexRoute
  AuthenticatedCatalogStoragesIndexRoute: typeof AuthenticatedCatalogStoragesIndexRoute
  AuthenticatedCatalogWarehousesIndexRoute: typeof AuthenticatedCatalogWarehousesIndexRoute
  AuthenticatedDocumentsAcceptanceIndexRoute: typeof AuthenticatedDocumentsAcceptanceIndexRoute
  AuthenticatedDocumentsBlendingIndexRoute: typeof AuthenticatedDocumentsBlendingIndexRoute
  AuthenticatedDocumentsDispatchIndexRoute: typeof AuthenticatedDocumentsDispatchIndexRoute
  AuthenticatedDocumentsInventoryReconciliationIndexRoute: typeof AuthenticatedDocumentsInventoryReconciliationIndexRoute
  AuthenticatedDocumentsOwnershipTransferIndexRoute: typeof AuthenticatedDocumentsOwnershipTransferIndexRoute
  AuthenticatedDocumentsPhysicalTransferIndexRoute: typeof AuthenticatedDocumentsPhysicalTransferIndexRoute
  AuthenticatedSystemSyncIndexRoute: typeof AuthenticatedSystemSyncIndexRoute
  AuthenticatedSystemUsersIndexRoute: typeof AuthenticatedSystemUsersIndexRoute
  AuthenticatedTransportRailWaybillsIndexRoute: typeof AuthenticatedTransportRailWaybillsIndexRoute
  AuthenticatedTransportTruckWaybillsIndexRoute: typeof AuthenticatedTransportTruckWaybillsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLedgerIndexRoute: AuthenticatedLedgerIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedCatalogBasesIndexRoute: AuthenticatedCatalogBasesIndexRoute,
  AuthenticatedCatalogCompaniesIndexRoute:
    AuthenticatedCatalogCompaniesIndexRoute,
  AuthenticatedCatalogPortsIndexRoute: AuthenticatedCatalogPortsIndexRoute,
  AuthenticatedCatalogProductGroupsIndexRoute:
    AuthenticatedCatalogProductGroupsIndexRoute,
  AuthenticatedCatalogProductTypesIndexRoute:
    AuthenticatedCatalogProductTypesIndexRoute,
  AuthenticatedCatalogProductsIndexRoute:
    AuthenticatedCatalogProductsIndexRoute,
  AuthenticatedCatalogStoragesIndexRoute:
    AuthenticatedCatalogStoragesIndexRoute,
  AuthenticatedCatalogWarehousesIndexRoute:
    AuthenticatedCatalogWarehousesIndexRoute,
  AuthenticatedDocumentsAcceptanceIndexRoute:
    AuthenticatedDocumentsAcceptanceIndexRoute,
  AuthenticatedDocumentsBlendingIndexRoute:
    AuthenticatedDocumentsBlendingIndexRoute,
  AuthenticatedDocumentsDispatchIndexRoute:
    AuthenticatedDocumentsDispatchIndexRoute,
  AuthenticatedDocumentsInventoryReconciliationIndexRoute:
    AuthenticatedDocumentsInventoryReconciliationIndexRoute,
  AuthenticatedDocumentsOwnershipTransferIndexRoute:
    AuthenticatedDocumentsOwnershipTransferIndexRoute,
  AuthenticatedDocumentsPhysicalTransferIndexRoute:
    AuthenticatedDocumentsPhysicalTransferIndexRoute,
  AuthenticatedSystemSyncIndexRoute: AuthenticatedSystemSyncIndexRoute,
  AuthenticatedSystemUsersIndexRoute: AuthenticatedSystemUsersIndexRoute,
  AuthenticatedTransportRailWaybillsIndexRoute:
    AuthenticatedTransportRailWaybillsIndexRoute,
  AuthenticatedTransportTruckWaybillsIndexRoute:
    AuthenticatedTransportTruckWaybillsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authInitRoute: authInitRoute,
  authSetupRoute: authSetupRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
