/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSetupRouteImport } from './routes/(auth)/setup'
import { Route as authInitRouteImport } from './routes/(auth)/init'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedLedgerIndexRouteImport } from './routes/_authenticated/ledger/index'
import { Route as AuthenticatedCargoFlowIndexRouteImport } from './routes/_authenticated/cargo-flow/index'
import { Route as AuthenticatedSystemUsersIndexRouteImport } from './routes/_authenticated/system/users/index'
import { Route as AuthenticatedSystemSyncIndexRouteImport } from './routes/_authenticated/system/sync/index'
import { Route as AuthenticatedOutgoingTruckIndexRouteImport } from './routes/_authenticated/outgoing/truck/index'
import { Route as AuthenticatedOutgoingDirectIndexRouteImport } from './routes/_authenticated/outgoing/direct/index'
import { Route as AuthenticatedOutgoingBunkeringIndexRouteImport } from './routes/_authenticated/outgoing/bunkering/index'
import { Route as AuthenticatedInternalReconciliationIndexRouteImport } from './routes/_authenticated/internal/reconciliation/index'
import { Route as AuthenticatedInternalPhysicalTransferIndexRouteImport } from './routes/_authenticated/internal/physical-transfer/index'
import { Route as AuthenticatedInternalOwnershipTransferIndexRouteImport } from './routes/_authenticated/internal/ownership-transfer/index'
import { Route as AuthenticatedInternalBlendingIndexRouteImport } from './routes/_authenticated/internal/blending/index'
import { Route as AuthenticatedIncomingTruckIndexRouteImport } from './routes/_authenticated/incoming/truck/index'
import { Route as AuthenticatedIncomingRailIndexRouteImport } from './routes/_authenticated/incoming/rail/index'
import { Route as AuthenticatedIncomingExternalIndexRouteImport } from './routes/_authenticated/incoming/external/index'
import { Route as AuthenticatedCatalogWarehousesIndexRouteImport } from './routes/_authenticated/catalog/warehouses/index'
import { Route as AuthenticatedCatalogStoragesIndexRouteImport } from './routes/_authenticated/catalog/storages/index'
import { Route as AuthenticatedCatalogProductsIndexRouteImport } from './routes/_authenticated/catalog/products/index'
import { Route as AuthenticatedCatalogProductTypesIndexRouteImport } from './routes/_authenticated/catalog/product-types/index'
import { Route as AuthenticatedCatalogProductGroupsIndexRouteImport } from './routes/_authenticated/catalog/product-groups/index'
import { Route as AuthenticatedCatalogPortsIndexRouteImport } from './routes/_authenticated/catalog/ports/index'
import { Route as AuthenticatedCatalogCompaniesIndexRouteImport } from './routes/_authenticated/catalog/companies/index'
import { Route as AuthenticatedCatalogBasesIndexRouteImport } from './routes/_authenticated/catalog/bases/index'
import { Route as AuthenticatedOutgoingTruckIdRouteImport } from './routes/_authenticated/outgoing/truck/$id'
import { Route as AuthenticatedOutgoingDirectIdRouteImport } from './routes/_authenticated/outgoing/direct/$id'
import { Route as AuthenticatedOutgoingBunkeringIdRouteImport } from './routes/_authenticated/outgoing/bunkering/$id'
import { Route as AuthenticatedInternalReconciliationIdRouteImport } from './routes/_authenticated/internal/reconciliation/$id'
import { Route as AuthenticatedInternalPhysicalTransferIdRouteImport } from './routes/_authenticated/internal/physical-transfer/$id'
import { Route as AuthenticatedInternalOwnershipTransferIdRouteImport } from './routes/_authenticated/internal/ownership-transfer/$id'
import { Route as AuthenticatedInternalBlendingIdRouteImport } from './routes/_authenticated/internal/blending/$id'
import { Route as AuthenticatedIncomingTruckIdRouteImport } from './routes/_authenticated/incoming/truck/$id'
import { Route as AuthenticatedIncomingRailIdRouteImport } from './routes/_authenticated/incoming/rail/$id'
import { Route as AuthenticatedIncomingExternalIdRouteImport } from './routes/_authenticated/incoming/external/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSetupRoute = authSetupRouteImport.update({
  id: '/(auth)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const authInitRoute = authInitRouteImport.update({
  id: '/(auth)/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLedgerIndexRoute =
  AuthenticatedLedgerIndexRouteImport.update({
    id: '/ledger/',
    path: '/ledger/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCargoFlowIndexRoute =
  AuthenticatedCargoFlowIndexRouteImport.update({
    id: '/cargo-flow/',
    path: '/cargo-flow/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersIndexRoute =
  AuthenticatedSystemUsersIndexRouteImport.update({
    id: '/system/users/',
    path: '/system/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemSyncIndexRoute =
  AuthenticatedSystemSyncIndexRouteImport.update({
    id: '/system/sync/',
    path: '/system/sync/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutgoingTruckIndexRoute =
  AuthenticatedOutgoingTruckIndexRouteImport.update({
    id: '/outgoing/truck/',
    path: '/outgoing/truck/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutgoingDirectIndexRoute =
  AuthenticatedOutgoingDirectIndexRouteImport.update({
    id: '/outgoing/direct/',
    path: '/outgoing/direct/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutgoingBunkeringIndexRoute =
  AuthenticatedOutgoingBunkeringIndexRouteImport.update({
    id: '/outgoing/bunkering/',
    path: '/outgoing/bunkering/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternalReconciliationIndexRoute =
  AuthenticatedInternalReconciliationIndexRouteImport.update({
    id: '/internal/reconciliation/',
    path: '/internal/reconciliation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternalPhysicalTransferIndexRoute =
  AuthenticatedInternalPhysicalTransferIndexRouteImport.update({
    id: '/internal/physical-transfer/',
    path: '/internal/physical-transfer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternalOwnershipTransferIndexRoute =
  AuthenticatedInternalOwnershipTransferIndexRouteImport.update({
    id: '/internal/ownership-transfer/',
    path: '/internal/ownership-transfer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternalBlendingIndexRoute =
  AuthenticatedInternalBlendingIndexRouteImport.update({
    id: '/internal/blending/',
    path: '/internal/blending/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncomingTruckIndexRoute =
  AuthenticatedIncomingTruckIndexRouteImport.update({
    id: '/incoming/truck/',
    path: '/incoming/truck/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncomingRailIndexRoute =
  AuthenticatedIncomingRailIndexRouteImport.update({
    id: '/incoming/rail/',
    path: '/incoming/rail/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncomingExternalIndexRoute =
  AuthenticatedIncomingExternalIndexRouteImport.update({
    id: '/incoming/external/',
    path: '/incoming/external/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogWarehousesIndexRoute =
  AuthenticatedCatalogWarehousesIndexRouteImport.update({
    id: '/catalog/warehouses/',
    path: '/catalog/warehouses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogStoragesIndexRoute =
  AuthenticatedCatalogStoragesIndexRouteImport.update({
    id: '/catalog/storages/',
    path: '/catalog/storages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductsIndexRoute =
  AuthenticatedCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductTypesIndexRoute =
  AuthenticatedCatalogProductTypesIndexRouteImport.update({
    id: '/catalog/product-types/',
    path: '/catalog/product-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductGroupsIndexRoute =
  AuthenticatedCatalogProductGroupsIndexRouteImport.update({
    id: '/catalog/product-groups/',
    path: '/catalog/product-groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogPortsIndexRoute =
  AuthenticatedCatalogPortsIndexRouteImport.update({
    id: '/catalog/ports/',
    path: '/catalog/ports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogCompaniesIndexRoute =
  AuthenticatedCatalogCompaniesIndexRouteImport.update({
    id: '/catalog/companies/',
    path: '/catalog/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogBasesIndexRoute =
  AuthenticatedCatalogBasesIndexRouteImport.update({
    id: '/catalog/bases/',
    path: '/catalog/bases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutgoingTruckIdRoute =
  AuthenticatedOutgoingTruckIdRouteImport.update({
    id: '/outgoing/truck/$id',
    path: '/outgoing/truck/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutgoingDirectIdRoute =
  AuthenticatedOutgoingDirectIdRouteImport.update({
    id: '/outgoing/direct/$id',
    path: '/outgoing/direct/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutgoingBunkeringIdRoute =
  AuthenticatedOutgoingBunkeringIdRouteImport.update({
    id: '/outgoing/bunkering/$id',
    path: '/outgoing/bunkering/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternalReconciliationIdRoute =
  AuthenticatedInternalReconciliationIdRouteImport.update({
    id: '/internal/reconciliation/$id',
    path: '/internal/reconciliation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternalPhysicalTransferIdRoute =
  AuthenticatedInternalPhysicalTransferIdRouteImport.update({
    id: '/internal/physical-transfer/$id',
    path: '/internal/physical-transfer/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternalOwnershipTransferIdRoute =
  AuthenticatedInternalOwnershipTransferIdRouteImport.update({
    id: '/internal/ownership-transfer/$id',
    path: '/internal/ownership-transfer/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternalBlendingIdRoute =
  AuthenticatedInternalBlendingIdRouteImport.update({
    id: '/internal/blending/$id',
    path: '/internal/blending/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncomingTruckIdRoute =
  AuthenticatedIncomingTruckIdRouteImport.update({
    id: '/incoming/truck/$id',
    path: '/incoming/truck/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncomingRailIdRoute =
  AuthenticatedIncomingRailIdRouteImport.update({
    id: '/incoming/rail/$id',
    path: '/incoming/rail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncomingExternalIdRoute =
  AuthenticatedIncomingExternalIdRouteImport.update({
    id: '/incoming/external/$id',
    path: '/incoming/external/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/init': typeof authInitRoute
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/cargo-flow/': typeof AuthenticatedCargoFlowIndexRoute
  '/ledger/': typeof AuthenticatedLedgerIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/incoming/external/$id': typeof AuthenticatedIncomingExternalIdRoute
  '/incoming/rail/$id': typeof AuthenticatedIncomingRailIdRoute
  '/incoming/truck/$id': typeof AuthenticatedIncomingTruckIdRoute
  '/internal/blending/$id': typeof AuthenticatedInternalBlendingIdRoute
  '/internal/ownership-transfer/$id': typeof AuthenticatedInternalOwnershipTransferIdRoute
  '/internal/physical-transfer/$id': typeof AuthenticatedInternalPhysicalTransferIdRoute
  '/internal/reconciliation/$id': typeof AuthenticatedInternalReconciliationIdRoute
  '/outgoing/bunkering/$id': typeof AuthenticatedOutgoingBunkeringIdRoute
  '/outgoing/direct/$id': typeof AuthenticatedOutgoingDirectIdRoute
  '/outgoing/truck/$id': typeof AuthenticatedOutgoingTruckIdRoute
  '/catalog/bases/': typeof AuthenticatedCatalogBasesIndexRoute
  '/catalog/companies/': typeof AuthenticatedCatalogCompaniesIndexRoute
  '/catalog/ports/': typeof AuthenticatedCatalogPortsIndexRoute
  '/catalog/product-groups/': typeof AuthenticatedCatalogProductGroupsIndexRoute
  '/catalog/product-types/': typeof AuthenticatedCatalogProductTypesIndexRoute
  '/catalog/products/': typeof AuthenticatedCatalogProductsIndexRoute
  '/catalog/storages/': typeof AuthenticatedCatalogStoragesIndexRoute
  '/catalog/warehouses/': typeof AuthenticatedCatalogWarehousesIndexRoute
  '/incoming/external/': typeof AuthenticatedIncomingExternalIndexRoute
  '/incoming/rail/': typeof AuthenticatedIncomingRailIndexRoute
  '/incoming/truck/': typeof AuthenticatedIncomingTruckIndexRoute
  '/internal/blending/': typeof AuthenticatedInternalBlendingIndexRoute
  '/internal/ownership-transfer/': typeof AuthenticatedInternalOwnershipTransferIndexRoute
  '/internal/physical-transfer/': typeof AuthenticatedInternalPhysicalTransferIndexRoute
  '/internal/reconciliation/': typeof AuthenticatedInternalReconciliationIndexRoute
  '/outgoing/bunkering/': typeof AuthenticatedOutgoingBunkeringIndexRoute
  '/outgoing/direct/': typeof AuthenticatedOutgoingDirectIndexRoute
  '/outgoing/truck/': typeof AuthenticatedOutgoingTruckIndexRoute
  '/system/sync/': typeof AuthenticatedSystemSyncIndexRoute
  '/system/users/': typeof AuthenticatedSystemUsersIndexRoute
}
export interface FileRoutesByTo {
  '/init': typeof authInitRoute
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/cargo-flow': typeof AuthenticatedCargoFlowIndexRoute
  '/ledger': typeof AuthenticatedLedgerIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/incoming/external/$id': typeof AuthenticatedIncomingExternalIdRoute
  '/incoming/rail/$id': typeof AuthenticatedIncomingRailIdRoute
  '/incoming/truck/$id': typeof AuthenticatedIncomingTruckIdRoute
  '/internal/blending/$id': typeof AuthenticatedInternalBlendingIdRoute
  '/internal/ownership-transfer/$id': typeof AuthenticatedInternalOwnershipTransferIdRoute
  '/internal/physical-transfer/$id': typeof AuthenticatedInternalPhysicalTransferIdRoute
  '/internal/reconciliation/$id': typeof AuthenticatedInternalReconciliationIdRoute
  '/outgoing/bunkering/$id': typeof AuthenticatedOutgoingBunkeringIdRoute
  '/outgoing/direct/$id': typeof AuthenticatedOutgoingDirectIdRoute
  '/outgoing/truck/$id': typeof AuthenticatedOutgoingTruckIdRoute
  '/catalog/bases': typeof AuthenticatedCatalogBasesIndexRoute
  '/catalog/companies': typeof AuthenticatedCatalogCompaniesIndexRoute
  '/catalog/ports': typeof AuthenticatedCatalogPortsIndexRoute
  '/catalog/product-groups': typeof AuthenticatedCatalogProductGroupsIndexRoute
  '/catalog/product-types': typeof AuthenticatedCatalogProductTypesIndexRoute
  '/catalog/products': typeof AuthenticatedCatalogProductsIndexRoute
  '/catalog/storages': typeof AuthenticatedCatalogStoragesIndexRoute
  '/catalog/warehouses': typeof AuthenticatedCatalogWarehousesIndexRoute
  '/incoming/external': typeof AuthenticatedIncomingExternalIndexRoute
  '/incoming/rail': typeof AuthenticatedIncomingRailIndexRoute
  '/incoming/truck': typeof AuthenticatedIncomingTruckIndexRoute
  '/internal/blending': typeof AuthenticatedInternalBlendingIndexRoute
  '/internal/ownership-transfer': typeof AuthenticatedInternalOwnershipTransferIndexRoute
  '/internal/physical-transfer': typeof AuthenticatedInternalPhysicalTransferIndexRoute
  '/internal/reconciliation': typeof AuthenticatedInternalReconciliationIndexRoute
  '/outgoing/bunkering': typeof AuthenticatedOutgoingBunkeringIndexRoute
  '/outgoing/direct': typeof AuthenticatedOutgoingDirectIndexRoute
  '/outgoing/truck': typeof AuthenticatedOutgoingTruckIndexRoute
  '/system/sync': typeof AuthenticatedSystemSyncIndexRoute
  '/system/users': typeof AuthenticatedSystemUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/init': typeof authInitRoute
  '/(auth)/setup': typeof authSetupRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cargo-flow/': typeof AuthenticatedCargoFlowIndexRoute
  '/_authenticated/ledger/': typeof AuthenticatedLedgerIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/incoming/external/$id': typeof AuthenticatedIncomingExternalIdRoute
  '/_authenticated/incoming/rail/$id': typeof AuthenticatedIncomingRailIdRoute
  '/_authenticated/incoming/truck/$id': typeof AuthenticatedIncomingTruckIdRoute
  '/_authenticated/internal/blending/$id': typeof AuthenticatedInternalBlendingIdRoute
  '/_authenticated/internal/ownership-transfer/$id': typeof AuthenticatedInternalOwnershipTransferIdRoute
  '/_authenticated/internal/physical-transfer/$id': typeof AuthenticatedInternalPhysicalTransferIdRoute
  '/_authenticated/internal/reconciliation/$id': typeof AuthenticatedInternalReconciliationIdRoute
  '/_authenticated/outgoing/bunkering/$id': typeof AuthenticatedOutgoingBunkeringIdRoute
  '/_authenticated/outgoing/direct/$id': typeof AuthenticatedOutgoingDirectIdRoute
  '/_authenticated/outgoing/truck/$id': typeof AuthenticatedOutgoingTruckIdRoute
  '/_authenticated/catalog/bases/': typeof AuthenticatedCatalogBasesIndexRoute
  '/_authenticated/catalog/companies/': typeof AuthenticatedCatalogCompaniesIndexRoute
  '/_authenticated/catalog/ports/': typeof AuthenticatedCatalogPortsIndexRoute
  '/_authenticated/catalog/product-groups/': typeof AuthenticatedCatalogProductGroupsIndexRoute
  '/_authenticated/catalog/product-types/': typeof AuthenticatedCatalogProductTypesIndexRoute
  '/_authenticated/catalog/products/': typeof AuthenticatedCatalogProductsIndexRoute
  '/_authenticated/catalog/storages/': typeof AuthenticatedCatalogStoragesIndexRoute
  '/_authenticated/catalog/warehouses/': typeof AuthenticatedCatalogWarehousesIndexRoute
  '/_authenticated/incoming/external/': typeof AuthenticatedIncomingExternalIndexRoute
  '/_authenticated/incoming/rail/': typeof AuthenticatedIncomingRailIndexRoute
  '/_authenticated/incoming/truck/': typeof AuthenticatedIncomingTruckIndexRoute
  '/_authenticated/internal/blending/': typeof AuthenticatedInternalBlendingIndexRoute
  '/_authenticated/internal/ownership-transfer/': typeof AuthenticatedInternalOwnershipTransferIndexRoute
  '/_authenticated/internal/physical-transfer/': typeof AuthenticatedInternalPhysicalTransferIndexRoute
  '/_authenticated/internal/reconciliation/': typeof AuthenticatedInternalReconciliationIndexRoute
  '/_authenticated/outgoing/bunkering/': typeof AuthenticatedOutgoingBunkeringIndexRoute
  '/_authenticated/outgoing/direct/': typeof AuthenticatedOutgoingDirectIndexRoute
  '/_authenticated/outgoing/truck/': typeof AuthenticatedOutgoingTruckIndexRoute
  '/_authenticated/system/sync/': typeof AuthenticatedSystemSyncIndexRoute
  '/_authenticated/system/users/': typeof AuthenticatedSystemUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/init'
    | '/setup'
    | '/sign-in'
    | '/cargo-flow/'
    | '/ledger/'
    | '/settings/'
    | '/incoming/external/$id'
    | '/incoming/rail/$id'
    | '/incoming/truck/$id'
    | '/internal/blending/$id'
    | '/internal/ownership-transfer/$id'
    | '/internal/physical-transfer/$id'
    | '/internal/reconciliation/$id'
    | '/outgoing/bunkering/$id'
    | '/outgoing/direct/$id'
    | '/outgoing/truck/$id'
    | '/catalog/bases/'
    | '/catalog/companies/'
    | '/catalog/ports/'
    | '/catalog/product-groups/'
    | '/catalog/product-types/'
    | '/catalog/products/'
    | '/catalog/storages/'
    | '/catalog/warehouses/'
    | '/incoming/external/'
    | '/incoming/rail/'
    | '/incoming/truck/'
    | '/internal/blending/'
    | '/internal/ownership-transfer/'
    | '/internal/physical-transfer/'
    | '/internal/reconciliation/'
    | '/outgoing/bunkering/'
    | '/outgoing/direct/'
    | '/outgoing/truck/'
    | '/system/sync/'
    | '/system/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/init'
    | '/setup'
    | '/sign-in'
    | '/'
    | '/cargo-flow'
    | '/ledger'
    | '/settings'
    | '/incoming/external/$id'
    | '/incoming/rail/$id'
    | '/incoming/truck/$id'
    | '/internal/blending/$id'
    | '/internal/ownership-transfer/$id'
    | '/internal/physical-transfer/$id'
    | '/internal/reconciliation/$id'
    | '/outgoing/bunkering/$id'
    | '/outgoing/direct/$id'
    | '/outgoing/truck/$id'
    | '/catalog/bases'
    | '/catalog/companies'
    | '/catalog/ports'
    | '/catalog/product-groups'
    | '/catalog/product-types'
    | '/catalog/products'
    | '/catalog/storages'
    | '/catalog/warehouses'
    | '/incoming/external'
    | '/incoming/rail'
    | '/incoming/truck'
    | '/internal/blending'
    | '/internal/ownership-transfer'
    | '/internal/physical-transfer'
    | '/internal/reconciliation'
    | '/outgoing/bunkering'
    | '/outgoing/direct'
    | '/outgoing/truck'
    | '/system/sync'
    | '/system/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/init'
    | '/(auth)/setup'
    | '/(auth)/sign-in'
    | '/_authenticated/'
    | '/_authenticated/cargo-flow/'
    | '/_authenticated/ledger/'
    | '/_authenticated/settings/'
    | '/_authenticated/incoming/external/$id'
    | '/_authenticated/incoming/rail/$id'
    | '/_authenticated/incoming/truck/$id'
    | '/_authenticated/internal/blending/$id'
    | '/_authenticated/internal/ownership-transfer/$id'
    | '/_authenticated/internal/physical-transfer/$id'
    | '/_authenticated/internal/reconciliation/$id'
    | '/_authenticated/outgoing/bunkering/$id'
    | '/_authenticated/outgoing/direct/$id'
    | '/_authenticated/outgoing/truck/$id'
    | '/_authenticated/catalog/bases/'
    | '/_authenticated/catalog/companies/'
    | '/_authenticated/catalog/ports/'
    | '/_authenticated/catalog/product-groups/'
    | '/_authenticated/catalog/product-types/'
    | '/_authenticated/catalog/products/'
    | '/_authenticated/catalog/storages/'
    | '/_authenticated/catalog/warehouses/'
    | '/_authenticated/incoming/external/'
    | '/_authenticated/incoming/rail/'
    | '/_authenticated/incoming/truck/'
    | '/_authenticated/internal/blending/'
    | '/_authenticated/internal/ownership-transfer/'
    | '/_authenticated/internal/physical-transfer/'
    | '/_authenticated/internal/reconciliation/'
    | '/_authenticated/outgoing/bunkering/'
    | '/_authenticated/outgoing/direct/'
    | '/_authenticated/outgoing/truck/'
    | '/_authenticated/system/sync/'
    | '/_authenticated/system/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authInitRoute: typeof authInitRoute
  authSetupRoute: typeof authSetupRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/setup': {
      id: '/(auth)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof authSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/init': {
      id: '/(auth)/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof authInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger/': {
      id: '/_authenticated/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof AuthenticatedLedgerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cargo-flow/': {
      id: '/_authenticated/cargo-flow/'
      path: '/cargo-flow'
      fullPath: '/cargo-flow/'
      preLoaderRoute: typeof AuthenticatedCargoFlowIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users/': {
      id: '/_authenticated/system/users/'
      path: '/system/users'
      fullPath: '/system/users/'
      preLoaderRoute: typeof AuthenticatedSystemUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/sync/': {
      id: '/_authenticated/system/sync/'
      path: '/system/sync'
      fullPath: '/system/sync/'
      preLoaderRoute: typeof AuthenticatedSystemSyncIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outgoing/truck/': {
      id: '/_authenticated/outgoing/truck/'
      path: '/outgoing/truck'
      fullPath: '/outgoing/truck/'
      preLoaderRoute: typeof AuthenticatedOutgoingTruckIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outgoing/direct/': {
      id: '/_authenticated/outgoing/direct/'
      path: '/outgoing/direct'
      fullPath: '/outgoing/direct/'
      preLoaderRoute: typeof AuthenticatedOutgoingDirectIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outgoing/bunkering/': {
      id: '/_authenticated/outgoing/bunkering/'
      path: '/outgoing/bunkering'
      fullPath: '/outgoing/bunkering/'
      preLoaderRoute: typeof AuthenticatedOutgoingBunkeringIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internal/reconciliation/': {
      id: '/_authenticated/internal/reconciliation/'
      path: '/internal/reconciliation'
      fullPath: '/internal/reconciliation/'
      preLoaderRoute: typeof AuthenticatedInternalReconciliationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internal/physical-transfer/': {
      id: '/_authenticated/internal/physical-transfer/'
      path: '/internal/physical-transfer'
      fullPath: '/internal/physical-transfer/'
      preLoaderRoute: typeof AuthenticatedInternalPhysicalTransferIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internal/ownership-transfer/': {
      id: '/_authenticated/internal/ownership-transfer/'
      path: '/internal/ownership-transfer'
      fullPath: '/internal/ownership-transfer/'
      preLoaderRoute: typeof AuthenticatedInternalOwnershipTransferIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internal/blending/': {
      id: '/_authenticated/internal/blending/'
      path: '/internal/blending'
      fullPath: '/internal/blending/'
      preLoaderRoute: typeof AuthenticatedInternalBlendingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incoming/truck/': {
      id: '/_authenticated/incoming/truck/'
      path: '/incoming/truck'
      fullPath: '/incoming/truck/'
      preLoaderRoute: typeof AuthenticatedIncomingTruckIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incoming/rail/': {
      id: '/_authenticated/incoming/rail/'
      path: '/incoming/rail'
      fullPath: '/incoming/rail/'
      preLoaderRoute: typeof AuthenticatedIncomingRailIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incoming/external/': {
      id: '/_authenticated/incoming/external/'
      path: '/incoming/external'
      fullPath: '/incoming/external/'
      preLoaderRoute: typeof AuthenticatedIncomingExternalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/warehouses/': {
      id: '/_authenticated/catalog/warehouses/'
      path: '/catalog/warehouses'
      fullPath: '/catalog/warehouses/'
      preLoaderRoute: typeof AuthenticatedCatalogWarehousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/storages/': {
      id: '/_authenticated/catalog/storages/'
      path: '/catalog/storages'
      fullPath: '/catalog/storages/'
      preLoaderRoute: typeof AuthenticatedCatalogStoragesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/products/': {
      id: '/_authenticated/catalog/products/'
      path: '/catalog/products'
      fullPath: '/catalog/products/'
      preLoaderRoute: typeof AuthenticatedCatalogProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/product-types/': {
      id: '/_authenticated/catalog/product-types/'
      path: '/catalog/product-types'
      fullPath: '/catalog/product-types/'
      preLoaderRoute: typeof AuthenticatedCatalogProductTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/product-groups/': {
      id: '/_authenticated/catalog/product-groups/'
      path: '/catalog/product-groups'
      fullPath: '/catalog/product-groups/'
      preLoaderRoute: typeof AuthenticatedCatalogProductGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/ports/': {
      id: '/_authenticated/catalog/ports/'
      path: '/catalog/ports'
      fullPath: '/catalog/ports/'
      preLoaderRoute: typeof AuthenticatedCatalogPortsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/companies/': {
      id: '/_authenticated/catalog/companies/'
      path: '/catalog/companies'
      fullPath: '/catalog/companies/'
      preLoaderRoute: typeof AuthenticatedCatalogCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/bases/': {
      id: '/_authenticated/catalog/bases/'
      path: '/catalog/bases'
      fullPath: '/catalog/bases/'
      preLoaderRoute: typeof AuthenticatedCatalogBasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outgoing/truck/$id': {
      id: '/_authenticated/outgoing/truck/$id'
      path: '/outgoing/truck/$id'
      fullPath: '/outgoing/truck/$id'
      preLoaderRoute: typeof AuthenticatedOutgoingTruckIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outgoing/direct/$id': {
      id: '/_authenticated/outgoing/direct/$id'
      path: '/outgoing/direct/$id'
      fullPath: '/outgoing/direct/$id'
      preLoaderRoute: typeof AuthenticatedOutgoingDirectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outgoing/bunkering/$id': {
      id: '/_authenticated/outgoing/bunkering/$id'
      path: '/outgoing/bunkering/$id'
      fullPath: '/outgoing/bunkering/$id'
      preLoaderRoute: typeof AuthenticatedOutgoingBunkeringIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internal/reconciliation/$id': {
      id: '/_authenticated/internal/reconciliation/$id'
      path: '/internal/reconciliation/$id'
      fullPath: '/internal/reconciliation/$id'
      preLoaderRoute: typeof AuthenticatedInternalReconciliationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internal/physical-transfer/$id': {
      id: '/_authenticated/internal/physical-transfer/$id'
      path: '/internal/physical-transfer/$id'
      fullPath: '/internal/physical-transfer/$id'
      preLoaderRoute: typeof AuthenticatedInternalPhysicalTransferIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internal/ownership-transfer/$id': {
      id: '/_authenticated/internal/ownership-transfer/$id'
      path: '/internal/ownership-transfer/$id'
      fullPath: '/internal/ownership-transfer/$id'
      preLoaderRoute: typeof AuthenticatedInternalOwnershipTransferIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internal/blending/$id': {
      id: '/_authenticated/internal/blending/$id'
      path: '/internal/blending/$id'
      fullPath: '/internal/blending/$id'
      preLoaderRoute: typeof AuthenticatedInternalBlendingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incoming/truck/$id': {
      id: '/_authenticated/incoming/truck/$id'
      path: '/incoming/truck/$id'
      fullPath: '/incoming/truck/$id'
      preLoaderRoute: typeof AuthenticatedIncomingTruckIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incoming/rail/$id': {
      id: '/_authenticated/incoming/rail/$id'
      path: '/incoming/rail/$id'
      fullPath: '/incoming/rail/$id'
      preLoaderRoute: typeof AuthenticatedIncomingRailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incoming/external/$id': {
      id: '/_authenticated/incoming/external/$id'
      path: '/incoming/external/$id'
      fullPath: '/incoming/external/$id'
      preLoaderRoute: typeof AuthenticatedIncomingExternalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCargoFlowIndexRoute: typeof AuthenticatedCargoFlowIndexRoute
  AuthenticatedLedgerIndexRoute: typeof AuthenticatedLedgerIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedIncomingExternalIdRoute: typeof AuthenticatedIncomingExternalIdRoute
  AuthenticatedIncomingRailIdRoute: typeof AuthenticatedIncomingRailIdRoute
  AuthenticatedIncomingTruckIdRoute: typeof AuthenticatedIncomingTruckIdRoute
  AuthenticatedInternalBlendingIdRoute: typeof AuthenticatedInternalBlendingIdRoute
  AuthenticatedInternalOwnershipTransferIdRoute: typeof AuthenticatedInternalOwnershipTransferIdRoute
  AuthenticatedInternalPhysicalTransferIdRoute: typeof AuthenticatedInternalPhysicalTransferIdRoute
  AuthenticatedInternalReconciliationIdRoute: typeof AuthenticatedInternalReconciliationIdRoute
  AuthenticatedOutgoingBunkeringIdRoute: typeof AuthenticatedOutgoingBunkeringIdRoute
  AuthenticatedOutgoingDirectIdRoute: typeof AuthenticatedOutgoingDirectIdRoute
  AuthenticatedOutgoingTruckIdRoute: typeof AuthenticatedOutgoingTruckIdRoute
  AuthenticatedCatalogBasesIndexRoute: typeof AuthenticatedCatalogBasesIndexRoute
  AuthenticatedCatalogCompaniesIndexRoute: typeof AuthenticatedCatalogCompaniesIndexRoute
  AuthenticatedCatalogPortsIndexRoute: typeof AuthenticatedCatalogPortsIndexRoute
  AuthenticatedCatalogProductGroupsIndexRoute: typeof AuthenticatedCatalogProductGroupsIndexRoute
  AuthenticatedCatalogProductTypesIndexRoute: typeof AuthenticatedCatalogProductTypesIndexRoute
  AuthenticatedCatalogProductsIndexRoute: typeof AuthenticatedCatalogProductsIndexRoute
  AuthenticatedCatalogStoragesIndexRoute: typeof AuthenticatedCatalogStoragesIndexRoute
  AuthenticatedCatalogWarehousesIndexRoute: typeof AuthenticatedCatalogWarehousesIndexRoute
  AuthenticatedIncomingExternalIndexRoute: typeof AuthenticatedIncomingExternalIndexRoute
  AuthenticatedIncomingRailIndexRoute: typeof AuthenticatedIncomingRailIndexRoute
  AuthenticatedIncomingTruckIndexRoute: typeof AuthenticatedIncomingTruckIndexRoute
  AuthenticatedInternalBlendingIndexRoute: typeof AuthenticatedInternalBlendingIndexRoute
  AuthenticatedInternalOwnershipTransferIndexRoute: typeof AuthenticatedInternalOwnershipTransferIndexRoute
  AuthenticatedInternalPhysicalTransferIndexRoute: typeof AuthenticatedInternalPhysicalTransferIndexRoute
  AuthenticatedInternalReconciliationIndexRoute: typeof AuthenticatedInternalReconciliationIndexRoute
  AuthenticatedOutgoingBunkeringIndexRoute: typeof AuthenticatedOutgoingBunkeringIndexRoute
  AuthenticatedOutgoingDirectIndexRoute: typeof AuthenticatedOutgoingDirectIndexRoute
  AuthenticatedOutgoingTruckIndexRoute: typeof AuthenticatedOutgoingTruckIndexRoute
  AuthenticatedSystemSyncIndexRoute: typeof AuthenticatedSystemSyncIndexRoute
  AuthenticatedSystemUsersIndexRoute: typeof AuthenticatedSystemUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCargoFlowIndexRoute: AuthenticatedCargoFlowIndexRoute,
  AuthenticatedLedgerIndexRoute: AuthenticatedLedgerIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedIncomingExternalIdRoute: AuthenticatedIncomingExternalIdRoute,
  AuthenticatedIncomingRailIdRoute: AuthenticatedIncomingRailIdRoute,
  AuthenticatedIncomingTruckIdRoute: AuthenticatedIncomingTruckIdRoute,
  AuthenticatedInternalBlendingIdRoute: AuthenticatedInternalBlendingIdRoute,
  AuthenticatedInternalOwnershipTransferIdRoute:
    AuthenticatedInternalOwnershipTransferIdRoute,
  AuthenticatedInternalPhysicalTransferIdRoute:
    AuthenticatedInternalPhysicalTransferIdRoute,
  AuthenticatedInternalReconciliationIdRoute:
    AuthenticatedInternalReconciliationIdRoute,
  AuthenticatedOutgoingBunkeringIdRoute: AuthenticatedOutgoingBunkeringIdRoute,
  AuthenticatedOutgoingDirectIdRoute: AuthenticatedOutgoingDirectIdRoute,
  AuthenticatedOutgoingTruckIdRoute: AuthenticatedOutgoingTruckIdRoute,
  AuthenticatedCatalogBasesIndexRoute: AuthenticatedCatalogBasesIndexRoute,
  AuthenticatedCatalogCompaniesIndexRoute:
    AuthenticatedCatalogCompaniesIndexRoute,
  AuthenticatedCatalogPortsIndexRoute: AuthenticatedCatalogPortsIndexRoute,
  AuthenticatedCatalogProductGroupsIndexRoute:
    AuthenticatedCatalogProductGroupsIndexRoute,
  AuthenticatedCatalogProductTypesIndexRoute:
    AuthenticatedCatalogProductTypesIndexRoute,
  AuthenticatedCatalogProductsIndexRoute:
    AuthenticatedCatalogProductsIndexRoute,
  AuthenticatedCatalogStoragesIndexRoute:
    AuthenticatedCatalogStoragesIndexRoute,
  AuthenticatedCatalogWarehousesIndexRoute:
    AuthenticatedCatalogWarehousesIndexRoute,
  AuthenticatedIncomingExternalIndexRoute:
    AuthenticatedIncomingExternalIndexRoute,
  AuthenticatedIncomingRailIndexRoute: AuthenticatedIncomingRailIndexRoute,
  AuthenticatedIncomingTruckIndexRoute: AuthenticatedIncomingTruckIndexRoute,
  AuthenticatedInternalBlendingIndexRoute:
    AuthenticatedInternalBlendingIndexRoute,
  AuthenticatedInternalOwnershipTransferIndexRoute:
    AuthenticatedInternalOwnershipTransferIndexRoute,
  AuthenticatedInternalPhysicalTransferIndexRoute:
    AuthenticatedInternalPhysicalTransferIndexRoute,
  AuthenticatedInternalReconciliationIndexRoute:
    AuthenticatedInternalReconciliationIndexRoute,
  AuthenticatedOutgoingBunkeringIndexRoute:
    AuthenticatedOutgoingBunkeringIndexRoute,
  AuthenticatedOutgoingDirectIndexRoute: AuthenticatedOutgoingDirectIndexRoute,
  AuthenticatedOutgoingTruckIndexRoute: AuthenticatedOutgoingTruckIndexRoute,
  AuthenticatedSystemSyncIndexRoute: AuthenticatedSystemSyncIndexRoute,
  AuthenticatedSystemUsersIndexRoute: AuthenticatedSystemUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authInitRoute: authInitRoute,
  authSetupRoute: authSetupRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
