export { LifecycleActions } from './lifecycle-actions'
export { DocumentHeader } from './document-header'
export { DocumentForm, useDocumentFormLock } from './document-form'
export { ChildItemsTable } from './child-items-table'
export { RelatedDocuments } from './related-documents'
export type { RelatedDocument } from './related-documents'
export { DocumentDetailPage } from './document-detail-page'
export type { DocumentDetailConfig } from './document-detail-page'
