pub mod request;
pub mod response;
pub mod validators;

/*
DTO macro contracts:

- #[request_dto]
  Adds derives: Debug, Deserialize, Serialize, Validate, ToSchema.
  Adds serde rename_all = "camelCase".
  For Decimal fields it applies string serde/schema representation.
  For request strings with length validation it also enforces non-blank validation.
  Parameters: none.

- #[response_dto]
  Adds derives: Debug, Serialize, ToSchema.
  Adds serde rename_all = "camelCase".
  Supports optional service field generation only when explicitly requested.
  Parameters:
  - no params: do not inject any service fields.
  - service_fields(common): inject created/updated/deleted timestamps and actors + origin_db_id.
  - service_fields(document): inject common fields + status + executed/reverted lifecycle fields.
  - service_fields(all): inject document fields + version.
  - service_fields(field_a, field_b, ...): inject only listed supported service fields.
  - service_fields(): explicit no-op (equivalent to no params).
*/

pub use request::{
  audit::{PushAuditLogRequest, PushAuditLogsRequest},
  catalog::{
    CreateBaseRequest,
    CreateCompanyRequest,
    CreatePortRequest,
    CreateProductGroupRequest,
    CreateProductRequest,
    CreateProductTypeRequest,
    CreateStorageRequest,
    CreateWarehouseRequest,
    UpdateBaseRequest,
    UpdateCompanyRequest,
    UpdatePortRequest,
    UpdateProductGroupRequest,
    UpdateProductRequest,
    UpdateProductTypeRequest,
    UpdateStorageRequest,
    UpdateWarehouseRequest,
  },
  document::{
    AcceptanceItemCompositeRequest,
    BlendingComponentCompositeRequest,
    BlendingResultCompositeRequest,
    CreateAcceptanceCompositeRequest,
    CreateAcceptanceItemRequest,
    CreateAcceptanceRequest,
    CreateBlendingComponentRequest,
    CreateBlendingCompositeRequest,
    CreateBlendingRequest,
    CreateBlendingResultRequest,
    CreateDispatchCompositeRequest,
    CreateDispatchItemRequest,
    CreateDispatchMeasurementRequest,
    CreateDispatchRequest,
    CreateInventoryAdjustmentRequest,
    CreateInventoryReconciliationCompositeRequest,
    CreateInventoryReconciliationRequest,
    CreateOwnershipTransferItemRequest,
    CreateOwnershipTransferRequest,
    CreatePhysicalTransferItemRequest,
    CreatePhysicalTransferRequest,
    CreateRailWagonManifestRequest,
    CreateRailWagonMeasurementRequest,
    CreateRailWagonWeightRequest,
    CreateRailWaybillRequest,
    CreateTruckWaybillItemRequest,
    CreateTruckWaybillRequest,
    CreateTruckWeightDocRequest,
    DispatchItemCompositeRequest,
    DispatchMeasurementCompositeRequest,
    InventoryAdjustmentCompositeRequest,
    OwnershipTransferItemCompositeRequest,
    PhysicalTransferItemCompositeRequest,
    RailWagonManifestCompositeRequest,
    RailWagonMeasurementCompositeRequest,
    RailWagonWeightCompositeRequest,
    RailWaybillCompositeRequest,
    TransportAcceptanceCompositeRequest,
    TruckWaybillCompositeRequest,
    TruckWaybillItemCompositeRequest,
    TruckWeightDocCompositeRequest,
    UpdateAcceptanceCompositeRequest,
    UpdateAcceptanceItemCompositeRequest,
    UpdateAcceptanceItemRequest,
    UpdateAcceptanceRequest,
    UpdateBlendingComponentCompositeRequest,
    UpdateBlendingComponentRequest,
    UpdateBlendingCompositeRequest,
    UpdateBlendingRequest,
    UpdateBlendingResultCompositeRequest,
    UpdateBlendingResultRequest,
    UpdateDispatchCompositeRequest,
    UpdateDispatchItemCompositeRequest,
    UpdateDispatchItemRequest,
    UpdateDispatchMeasurementCompositeRequest,
    UpdateDispatchMeasurementRequest,
    UpdateDispatchRequest,
    UpdateInventoryAdjustmentCompositeRequest,
    UpdateInventoryAdjustmentRequest,
    UpdateInventoryReconciliationCompositeRequest,
    UpdateInventoryReconciliationRequest,
    UpdateOwnershipTransferCompositeRequest,
    UpdateOwnershipTransferItemCompositeRequest,
    UpdateOwnershipTransferItemRequest,
    UpdateOwnershipTransferRequest,
    UpdatePhysicalTransferCompositeRequest,
    UpdatePhysicalTransferItemCompositeRequest,
    UpdatePhysicalTransferItemRequest,
    UpdatePhysicalTransferRequest,
    UpdateRailWagonManifestCompositeRequest,
    UpdateRailWagonManifestRequest,
    UpdateRailWagonMeasurementCompositeRequest,
    UpdateRailWagonMeasurementRequest,
    UpdateRailWagonWeightCompositeRequest,
    UpdateRailWagonWeightRequest,
    UpdateRailWaybillCompositeRequest,
    UpdateRailWaybillRequest,
    UpdateTruckWaybillCompositeRequest,
    UpdateTruckWaybillItemCompositeRequest,
    UpdateTruckWaybillItemRequest,
    UpdateTruckWaybillRequest,
    UpdateTruckWeightDocRequest,
  },
  ledger::LedgerEntryLookupRequest,
  query::{
    AcceptanceDocumentQueryParams,
    AcceptanceFlatQueryParams,
    BlendingDocumentQueryParams,
    BlendingFlatQueryParams,
    CargoFlowQueryParams,
    DispatchDocumentQueryParams,
    DispatchFlatQueryParams,
    EmbedParams,
    OwnershipTransferDocumentQueryParams,
    OwnershipTransferFlatQueryParams,
    PaginationParams,
    PhysicalTransferDocumentQueryParams,
    PhysicalTransferFlatQueryParams,
    RailReceiptPipelineQueryParams,
    RailWaybillDocumentQueryParams,
    ReconciliationDocumentQueryParams,
    ReconciliationFlatQueryParams,
    TruckDispatchPipelineQueryParams,
    TruckReceiptPipelineQueryParams,
    TruckWaybillDocumentQueryParams,
  },
  sync::{
    AuditLogQueryRequest,
    AwaitCycleQueryRequest,
    OutboundLogsQueryRequest,
    PullAuditLogsQueryRequest,
    SyncStatusQueryRequest,
    UpsertWatermarkRequest,
  },
  system::{
    AddBaseAssignmentRequest,
    ChangePasswordRequest,
    CompleteInitializationRequest,
    CreateUserRequest,
    LoginRequest,
    RefreshTokenRequest,
    UpdateCentralApiUrlRequest,
    UpdateUserRequest,
  },
};
pub use response::{
  audit::AuditLogResponse,
  catalog::{
    BaseResponse,
    CompanyResponse,
    PortResponse,
    ProductGroupResponse,
    ProductResponse,
    ProductTypeResponse,
    StorageResponse,
    WarehouseResponse,
  },
  dev::SeedResult,
  document::{
    AcceptanceCompositeResponse,
    AcceptanceFlatRow,
    AcceptanceItemResponse,
    AcceptanceResponse,
    BlendingComponentResponse,
    BlendingCompositeResponse,
    BlendingFlatRow,
    BlendingResponse,
    BlendingResultResponse,
    DispatchCompositeResponse,
    DispatchFlatRow,
    DispatchItemResponse,
    DispatchMeasurementResponse,
    DispatchResponse,
    InventoryAdjustmentResponse,
    InventoryReconciliationCompositeResponse,
    InventoryReconciliationResponse,
    OwnershipTransferFlatRow,
    OwnershipTransferItemResponse,
    OwnershipTransferResponse,
    PhysicalTransferFlatRow,
    PhysicalTransferItemResponse,
    PhysicalTransferResponse,
    RailWagonManifestResponse,
    RailWagonMeasurementResponse,
    RailWagonWeightResponse,
    RailWaybillCompositeResponse,
    RailWaybillResponse,
    ReconciliationFlatRow,
    TruckWaybillCompositeResponse,
    TruckWaybillItemResponse,
    TruckWaybillResponse,
    TruckWeightDocResponse,
  },
  flow::{
    CargoFlowFlatRow,
    CargoFlowPageResponse,
    RailReceiptPipelineResponse,
    TruckDispatchPipelineResponse,
    TruckReceiptPipelineResponse,
  },
  ledger::LedgerEntryResponse,
  sync::{
    AwaitCycleResponse,
    PullAuditLogsResponse,
    PushAuditLogsResponse,
    SyncStatusResponse,
    SyncWatermarkResponse,
  },
  system::{
    BaseAssignmentResponse,
    DatabaseInstanceResponse,
    HealthData,
    LocalResponse,
    LoginResponse,
    NodeStatusResponse,
    OperationMessageResponse,
    RefreshTokenResponse,
    RoleResponse,
    UserResponse,
  },
};
